### ISSUE TITLE
0.8.2 broken: (EXIT) no process

### ISSUE THREAD

**Issue by waynehoover** [edgurgel/httpoison#126]
With version 0.8.2 installed in a new project I get the below error, 0.8.1 doesn't have this issue.

```
iex(2)> HTTPoison.start
{:ok, []}
iex(3)> HTTPoison.get "http://google.com"
** (exit) exited in: :gen_server.call(:hackney_manager, {:new_request, #PID<0.168.0>, #Reference<0.0.2.1764>, {:client, :undefined, {:metrics_ng, :metrics_dummy}, :hackney_tcp_transport, 'google.com', 80, "google.com", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, nil}}, :infinity)
    ** (EXIT) no process
       (stdlib) gen_server.erl:212: :gen_server.call/3
      (hackney) src/hackney_manager.erl:66: :hackney_manager.init_request/1
      (hackney) src/hackney_manager.erl:56: :hackney_manager.new_request/1
      (hackney) src/hackney_connect.erl:184: :hackney_connect.socket_from_pool/4
      (hackney) src/hackney_connect.erl:36: :hackney_connect.connect/5
      (hackney) src/hackney.erl:321: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:396: HTTPoison.Base.request/9
```

**Comment by teerawat1992** [comment]
I'm facing the same issue :confused: 
```
** (CaseClauseError) no case clause matching: {:error, {{:EXIT, {{:badmatch, :undefined}, [{:hackney_util, :maybe_apply_defaults, 2, [file: 'src/hackney_util.erl', line: 68]}, {:hackney_pool, :start_link, 2, [file: 'src/hackney_pool.erl', line: 203]}, {:supervisor, :do_start_child, 2, [file: 'supervisor.erl', line: 358]}, {:supervisor, :handle_start_child, 2, [file: 'supervisor.erl', line: 717]}, {:supervisor, :handle_call, 3, [file: 'supervisor.erl', line: 415]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 629]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 661]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}, {:child, :undefined, :default, {:hackney_pool, :start_link, [:default, [name: :default]]}, :permanent, 10000, :worker, [:hackney_pool]}}}
      (hackney) src/hackney_pool.erl:177: :hackney_pool.do_start_pool/2
      (hackney) src/hackney_pool.erl:65: :hackney_pool.checkout/4
      (hackney) src/hackney_connect.erl:186: :hackney_connect.socket_from_pool/4
      (hackney) src/hackney_connect.erl:36: :hackney_connect.connect/5
      (hackney) src/hackney.erl:321: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:396: HTTPoison.Base.request/9
```

**Comment by nigelramsay** [comment]
We have noticed that Hackney has recently (1.5.5) defined a `mix.esx` file.  See https://github.com/benoitc/hackney/commit/e37504fa8706f6d66cc77f0428179a549d226a21

A work around in the short term is to add the following line to your `config.esx` file:

```
config :hackney, timeout: :infinite, max_connections: 5
```

**Comment by polymetis** [comment]
+1 thanks @nigelramsay

**Comment by tallakt** [comment]
Another workaround that worked for me was just freezing the hackney version for now, in `mix.exs`:

```
  defp deps do
    [
     {:hackney, "== 1.5.2"}, # bug introduced in 1.5.5
     {:httpoison, "~> 0.8.0"}]
  end

```

**Comment by nigelramsay** [comment]
@tallakt that works for me thanks.

**Comment by edgurgel** [comment]
Can you folks try to update hackney?

`mix deps.update hackney`

**Comment by tallakt** [comment]
It's working for me now with hackney v 1.5.9

Thanks

**Comment by edgurgel** [comment]
Awesome!
