### ISSUE TITLE
warnings from Elixir 1.4-rc.1 when using HTTPoison.Base

### ISSUE THREAD

**Issue by paulswartz** [edgurgel/httpoison#200]
```
warning: making private functions (process_response_body/1 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/v3_api.ex:2: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (process_headers/1 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/v3_api.ex:2: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (process_status_code/1 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/v3_api.ex:2: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (process_url/1 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/v3_api.ex:2: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (process_request_body/1 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/v3_api.ex:2: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (process_response_chunk/1 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/v3_api.ex:2: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6

warning: making private functions (process_request_headers/1 in this case) overridable is deprecated
  (elixir) lib/module.ex:815: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  lib/v3_api.ex:2: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6
```

I'll investigate more later, but I'd suspect that making them public functions would address this.

**Comment by edgurgel** [comment]
Yeah I think we just need to change them to be `def` instead of `defp`. Thanks for the report!

**Comment by agustif** [comment]
Thanks, I was on 0.9 and updating to master fixed the warnings too!!

One tries to ignore them ,but when they stack up they reall fugly the iex -S mix command start
