### ISSUE TITLE
Dynamically adding headers causes `List.to_string` conversion issues

### ISSUE THREAD

**Issue by OmanF** [edgurgel/httpoison#349]
When trying to add headers dynamically, that is, add headers on the actual call to a list of default headers already defined, I get an `ArgumentError` error.

**The situation** (scheme, of course):
```elixir
defmodule Trial do
  @def_headers [{"User-agent", "myUser"}]

  def my_req(verb, endpoint, body, headers \\ [], opts \\ []) do
    HTTPoison.request!(verb, endpoint, body, Keyword.merge(headers, @def_headers), [])
  end
end

Trial.my_req(verb, endpoint, body, [{"Content-Length", "0"}], [])
```

**The outcome**:
```
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[{"Content-Length", "0"}]

    (elixir) lib/list.ex:826: List.to_string/1
    (gist_handler) lib/client.ex:28: GistHandler.Client.contact_api!/5
```

**Note**:
* This happens for **any** `orddict` I used (e.g. [{"Content-Length", 0}], [{"Content-Type", "application/json"}]... everything).
* Tried using `apply(HTTPoison, [rest of params here...]) -- same error.
* This happens when I concatenate the `@def_headers` with the passed headers either via `Keyword.merge` or `++` (or the equivalent `Enum.concat`).
* **This happens whether I do the concatenation on the call itself (like shown above), or if the concatenated list is merged ahead-of-time and passed in as a single list!**
* Surprisingly, if **there are no** dynamic headers passed, i.e. call goes through **with only `@def_headers`**, everything works fine (but I need to be able to pass headers dynamically).

**Comment by OmanF** [comment]
Sorry, my bad, I misplaced a variable which cascaded and caused the issue.
Not an issue!!!
