### ISSUE TITLE
Module :leex is not available

### ISSUE THREAD

**Issue by aawilson** [edgurgel/httpoison#82]
Environment is Ubuntu 12.04, using the default Elixir install (via erlang-solutions_1.0_all.deb addition to package sources). The resulting Elixir version is 1.1.0, and erlang is 7.1 with otp release 18 (but I can't figure out how to get the specific minor version on Ubuntu). Floki is 0.6 (and I've also tried 0.6.1). I'm getting this:

```
    # mix deps.compile floki
    ==> floki
    could not compile dependency :floki, "mix compile" failed. You can recompile this dependency with "mix deps.compile floki", update it with "mix deps.update floki" or clean it with "mix deps.clean floki"
    ** (UndefinedFunctionError) undefined function: :leex.file/2 (module :leex is not available)
        :leex.file('src/floki_selector_lexer.xrl', [scannerfile: 'src/floki_selector_lexer.erl', report: true])
        (mix) lib/mix/compilers/erlang.ex:84: anonymous fn/3 in Mix.Compilers.Erlang.compile/3
        (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
        (mix) lib/mix/compilers/erlang.ex:83: Mix.Compilers.Erlang.compile/3
        (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1043: Enum.map/2
        (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
```

**Comment by aawilson** [comment]
Ah, I think I see the issue. Evidently it's possible to install only a very small subset of OTP with Erlang:

```
2> code:ensure_loaded(leex).
{error,nofile}
```

This is clearly not your issue, so I'll close this.

**Comment by edgurgel** [comment]
:+1:
